title: Quantum Sensing and Machine Learning applied to Object Monitoring
email: fertmeneses@gmail.com
logo: assets/web_face.png
description: Object monitoring application based on quantum magnetic sensing and artificial intelligence, by Fernando Meneses.
show_downloads: True
#google_analytics: G-14XGKWTF54
theme: jekyll-theme-minimal
